// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Models;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("StoreApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 17000m,
                            ProductName = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Price = 1700m,
                            ProductName = "Com"
                        },
                        new
                        {
                            Id = 3,
                            Price = 170m,
                            ProductName = "Comp"
                        },
                        new
                        {
                            Id = 4,
                            Price = 170m,
                            ProductName = "Compu"
                        },
                        new
                        {
                            Id = 5,
                            Price = 17m,
                            ProductName = "Comput"
                        },
                        new
                        {
                            Id = 6,
                            Price = 1m,
                            ProductName = "Compute"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
